// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5qJysFenn1xxi7pppthSAOKe0_cbLyNU',
    appId: '1:1067478327362:android:6a5a34005ffe2cbe654ddb',
    messagingSenderId: '1067478327362',
    projectId: 'billing-app-c6ec1',
    storageBucket: 'billing-app-c6ec1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeD--nk_HRdpwp_1C4NmxZ7oq5RNlr0xo',
    appId: '1:1067478327362:web:c4d26ad54d5bb958654ddb',
    messagingSenderId: '1067478327362',
    projectId: 'billing-app-c6ec1',
    authDomain: 'billing-app-c6ec1.firebaseapp.com',
    storageBucket: 'billing-app-c6ec1.firebasestorage.app',
    measurementId: 'G-CTM10HNGLS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_qxC45UnFzFKcvQDVS3XITedPciWDpU',
    appId: '1:1067478327362:ios:9fb9a70769bd03be654ddb',
    messagingSenderId: '1067478327362',
    projectId: 'billing-app-c6ec1',
    storageBucket: 'billing-app-c6ec1.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_qxC45UnFzFKcvQDVS3XITedPciWDpU',
    appId: '1:1067478327362:ios:9fb9a70769bd03be654ddb',
    messagingSenderId: '1067478327362',
    projectId: 'billing-app-c6ec1',
    storageBucket: 'billing-app-c6ec1.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeD--nk_HRdpwp_1C4NmxZ7oq5RNlr0xo',
    appId: '1:1067478327362:web:498f410fbe5dd9a2654ddb',
    messagingSenderId: '1067478327362',
    projectId: 'billing-app-c6ec1',
    authDomain: 'billing-app-c6ec1.firebaseapp.com',
    storageBucket: 'billing-app-c6ec1.firebasestorage.app',
    measurementId: 'G-WF56FQZW01',
  );

}